name: C/C++ CI

on:
  push:
    branches: [ master, develop, test-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake -DASL_TESTS=ON -DASL_BUILD_SHARED=OFF ..
    - name: make
      run: |
        cd build
        cmake --build .
    - name: test
      run: |
        cd build
        ctest --output-on-failure
