name: C/C++ CI

on:
  push:
    branches: [ master, develop, test-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: none #${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake -DASL_TESTS=ON -DASL_BUILD_SHARED=OFF ..
    - name: make
      run: |
        cd build
        cmake --build .
    - name: test
      run: |
        cd build
        ctest --output-on-failure

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: doc
      run: |
        sudo apt-get install doxygen
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
        make DOC
        cd ../..
        git clone -b gh-pages https://github.com/aslze/asl-doc
        cd asl-doc
        git config user.name "aslze"
        cp -rf ../asl/build/doc/* .
        git add --all
        git commit -m "Update documentation" -a
        git push
        