name: Documentation

on: workflow_dispatch

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: doc
      env:
        DOCTOK: ${{ secrets.DOC_TOKEN }}
      run: |
        sudo apt-get install doxygen
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
        make DOC
        cd ../..
        git clone -b gh-pages https://x-access-token:${DOCTOK}@github.com/aslze/asl-doc.git
        cd asl-doc
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        cp -rf ../asl/build/doc/* .
        git add --all
        git commit -m "Update documentation" -a && git push || echo "Documentation already up-to-date"
        