name: Documentation

on: workflow_dispatch

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: doc
      env:
        DOCTOK: ${{ secrets.DOCTOK }}
      run: |
        sudo apt-get install doxygen
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
        make DOC
        cd ../..
        git clone -b gh-pages https://github.com/aslze/asl-doc
        cd asl-doc
        git config user.name "aslze"
        cp -rf ../asl/build/doc/* .
        git add --all
        git commit -m "Update documentation" -a && git push https://aslze:$DOCTOK@github.com/aslze/asl-doc.git || echo "Documentation already up-to-date"
        