name: Build and test extended

on:
  workflow_dispatch:
    inputs:
      use_tls:
        description: "Use TLS"
        type: boolean
        default: false
      mbedtls_version:
        description: "MbedTLS version"
        type: string
        required: false
        default: "3.6.4"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, windows-2025-vs2026, macos-14]

    steps:
    - uses: actions/checkout@v6
    - name: configure
      shell: bash
      env:
        USE_TLS: ${{ inputs.use_tls }}
        MBEDTLS_VER: ${{ inputs.mbedtls_version }}
      run: |
        ARGS=()
        if [[ "$USE_TLS" == "true" ]]; then
          ARGS+=(-DASL_TLS=ON)
          ARGS+=(-DASL_MBEDTLS_VER=$MBEDTLS_VER)
        fi
        mkdir build
        cd build
        cmake -DASL_TESTS=ON -DASL_BUILD_SHARED=OFF -DASL_TEST_NET=ON -DASL_FETCH=ON "${ARGS[@]}" ..
    - name: make
      run: |
        cd build
        cmake --build .
    - name: test
      run: |
        cd build
        ctest --output-on-failure
